services:
  - type: web
    name: PortFolio
    runtime: python
    buildCommand: |
      pip install django gunicorn whitenoise psycopg2-binary
      python manage.py collectstatic --noinput
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: "django-insecure-s=n-569c-3=c6#qw(&u_2!=8bi==*8s8s^yo5*5)o)m!vg1(58"
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: OmniCipher.onrender.com